// --- START OF FILE database-nama.js ---

const databaseNama = {
    indonesia: {
        // Nama-nama dikelompokkan berdasarkan suku
        jawa: {
            laki: ["Budi Santoso", "Joko Susanto", "Eko Prasetyo", "Hendra Gunawan", "Arif Wibowo", "Aditya Nugroho", "Bayu Pratama", "Teguh Hidayat", "Dimas Setiawan", "Yoga Permana", "Wahyu Sudrajat", "Agus Wijaya", "Hanif Sjahbandi", "Rizky Ridho", "Muhammad Ferarri", "Akbar Arjunsyah", "Rio Fahmi", "Raka Cahyana", "Doni Alamsyah", "Rusdi Prasojo", "Agus Sumandi", "Susilo Ivan Budiaman", "Febri Hariyadi", "Dimas Hehanusa", "Fitrul Rustapa", "Zulfikli Lukmansyah", "Dedi Kusnandar", "Adam Alis"],
            perempuan: ["Siti Lestari", "Dewi Anggraini", "Ratih Ratnasari", "Ani Puspita", "Indah Permata", "Putri Wulandari", "Citra Handayani", "Wulan Novita", "Rina Agustina", "Fitri Rahmawati", "Dian Utami", "Lia Amelia", "Maya Sari", "Sri Wahyuni", "Annisa Fauziah", "Mega Damayanti", "Yuli Julianti", "Devi Sekarwangi", "Dewi Oktavia", "Asri Noviani", "Fitri Yuliani Kanaya", "Harti Melati", "Rani Arianty", "Suci Lestarii", "Intan Andini", "Putri Ayu Cahya", "Sulistia Insani", "Yunita Rahmanafisaa", "Lintang Chandramawati", "Siska Dwi Lestari", "Jelita Sandra Putri", "Desy Rahmat Setiawan", "Shinta Ratnasari", "Santi Winarti", "Sri Wahyuni", "Fitria Nuraini", "Tita Rizki Rahmawati", "Yayu Sri Rahayu", "Dewi Ratnasari", "Ayu Yulianti", "Agustina Dewanti", "Megawati Shabrina", "Husna Andrianti"]
        },
        sunda: {
            laki: ["Dadan Ramdanii", "Andi Kusnandi", "Aditya Hikmatiar", "Afiw Firmansyah", "Ujang Kurniawan", "Angga Saputra", "Sandi Permadi", "Angga Pillian", "Dhika Ahmad Maulana", "Egi Yanuar", "Rizky Maulana", "Agung Gunandar", "Andre Yanuar Utami", "Paldi Alip Utama", "Reza Syahrul Maulana", "Rizal Fahrurozi", "Irsan Jaelani", "Irman Maulana", "Andri Ramadhani", "Fadhlir Satriana", "Wawan Kurniawan", "Irfan Hasbalah", "Andi Nurhidayat", "Yoga Pratama Syaputra", "Farhan Muhamad", "Fikri Mauludi", "Galih Gumilang", "Padilah Fadry", "Arul Ardiansyah", "Dian Nurhidayat", "Fahmi Lukman", "Zikri Nurjaman", "Muhammad Wildan", "Gilang Purnama", "Teddy Supriyaddy", "Rian Oktapiana", "Rahmat Fauzi", "Sendi Darmawan", "Faisal Ramdani", "Aep Saepulloh", "Hendra Mulyanto", "Irham Ahmad", "Rian Prayogi", "Rendi Eriansyah", "Jujun Junaedi", "Azis Setiawan", "Fauzi Ridwan", "Indra Wiguna", "Ripan Adriansyah", "Saepul Kalaider", "Andri Maulana", "Sansan Mutamar Sidik", "Dani Maulana", "Ade Ilham", "Jajang Herdiansyah", "Dikri Faujan", "Husni Ramdhan", "Febri Pirmansyah", "Ryan Gunawan", "Erwin Maulana", "Andriansyah Hermawan", "Afrizal Pratama", "Rahmat Hidayat", "Gani Abdulrahman", "Farhan Ardiansyah", "Kakang Rudianto", "Ahmad Jufrianto", "Edo Febriansyah", "Rezaldi Permadi", "Henhen Herdiana", "Adzikry Fadillah", "Ryan Kurnia", "Arsan Maulana", "Yandi Sofyan"],
            perempuan: ["Risma Julianti", "Windi Herdiyanti", "Salsabilla Novita", "Riantri Nurhasanah", "Desti Risayanti", "Erika Sumartika", "Syifa Novita", "Nina Karlina", "Sani Rahmawati", "Windia priliyanti", "Tarisah Sofiah", "Astri Febryanti", "Idah Saidahh", "Allmy Mila", "Gina Gania", "Nyimassa Turoh", "Rena Sapitri", "Diah Wulandari", "Delia Shelly", "Windy Rahmayanti", "Neng Ciaa", "Sarah Apriliani", "Mela melani Amalia", "Fitria Ramdani", "Ririn Supiatin", "Rahma Dita", "Hasna Permatasari", "Siti Rafa Fatimah", "Sri Aprilia", "Anisa suliastri", "Anne Handayani", "Rahma Kania Utami", "Neni Supriatni", "Syifa Hadju", "Siska Rosita", "Tania Lailandina", "Chaca Salsabilla", "Fitri Andraeni", "Ernii Nurhasanah", "Revi Sulastri", "Ani Nuranii", "Linaa Agustina", "Sekah Agustina", "Alin Herlina", "Ismi Napisah", "Wulan Andriani", "Tira Maulidina", "Nesvi Syabantika", "Mega Agustina", "Vera Maulidani", "Chika Jessica", "Yeni Mulia Mustaqimah", "Gita Almidott", "Gita Yulianti", "Melani Ramlan", "Esti Restiani", "Indri Nurahman Fauzi", "Risma Pebrianti", "Mia Maulina", "Salsa Dila Nurlita", "Eva Halipah", "Julia Rahmawati", "Resti Nursafitri", "Nisa Masitoh", "Riri Ismilah", "Ristna Ayulia Agustina", "Anni Mullyani", "Irma Indriani", "Reni Rahmaeni", "Divia Febriani", "Ayra Sri Rahayu", "Yeni Rahmawati", "Dita Aulia", "Fuji Apriliyani", "Asri Nuryanti", "Isna Nurani", "Nurlia Ameliana", "Hilda Dwi Anjani", "Dera Sagita", "Resti Amelia", "Tia Amelia", "Nadila Jodi Putri", "Lisda Nissa Sarhen", "Hani Agustina", "Riska Aisyah", "Nurfitri Azizah", "Nadhilah Nuramalina", "Riska Rahmayani", "Lia Sri Rahayu", "Ginaa Herlina", "Novi Siti Nurmala", "Erni Nurulhusna", "Nispa Nurhamidah", "Nurul Nurliawati", "Rita Rismayanti", "Rida Dian Nurdiana", "Aidina Wiratmadja", "Rani Krismayanti", "Jihan Nabila", "Anisa Rosalia", "Dini Nurdiyanti", "Rida Mardiana", "Usi Indriani", "Inez Agustin", "Sifa Despiana", "Ica Nisa Nurasiah", "Ratih suryani", "Oktaviani Wina", "Via Nuraeni", "Yati Aprianti", "Resaa Safira", "Dewi Nur Alia", "Nisha Nurfitria Amalia", "Pitri Dwi Rahmawati", "Nandiya Juliyanti", "Ratiih Aprillia", "Indriyani gitaa", "Desi Suminar", "Delis Intan Junia", "Rika Sri Wahyuni", "Risma Amalia", "Sari Ningsih", "Devi Fadilah", "Susi Lawati", "Tety Nurhayaty", "Dini Aulia", "Alika Prihatiwi", "Wike Fauziah", "Arini Aelda Nurfitria", "Triska Kurniani", "Taris Aisi", "Kartika Mairessi", "Safirah Sukosulistiowani", "Khansa Paramitha", "Athirah Mulyanti", "Feby Sharifa", "Ayu Resa", "Della Fatimah", "Nanda Palupi", "Fauzia Obara", "Saliha Kamilia Sjukri", "Citra Juwita", "Tessa Sylvia Lestari", "Nella Amira", "Christy Fitriani", "Karima Arahman", "Sephira Tika", "Inneke Varensia", "Sari Primavera", "Muthia Dinanti", "Irene Prasanti", "Gleny Melfriza", "Rahmah Azhari"]
        },
        batak: {
            laki: ["Tobias Hutabalian", "Benni Sitohang", "Maruli Tampubolon", "Daniel Sinaga", "Putra Siregar", "Kevin Simanjuntak", "Rahmat Hidayat Lubis", "Jordan Nainggolan", "Hotman Paris Hutapea", "David Panjaitan", "Samuel Pangaribuan", "Gideon Nababan", "Franky Sihombing", "Judika Sihotang"],
            perempuan: ["Maria Simorangkir", "Astrid Tiar Panjaitan", "Nadya Hutagalung", "Lyodra Ginting", "Ruhut Sitompul", "Annisa Pohan", "Martha Simanjuntak", "Yessica Tamara Sitorus", "Tiurmaida Sitompul", "Rosalina Pasaribu", "Friska Nababan", "Dewi Marpaung", "Lidya Gurning", "Putri Lubis"]
        },
        maluku: {
            laki: ["Glenn Fredly Latuihamallo", "Ellyas Pical", "Chico Jericho", "Reza Rahadian Matulessy", "Utha Likumahuwa", "Benny Tupan", "Jonas Rivanno Wattimena", "George Tanasale", "Yance Sopacua", "Marvey Kaya", "Andre Hehanussa", "Christian Soumokil", "Yosafat Aipassa", "Ronny Wabia"],
            perempuan: ["Prilly Latuconsina", "Ruth Sahanaya", "Monita Tahalea", "Angelina Sondakh", "Melky Goeslaw", "Kamasean Matthews", "Regina Ivanova", "Audrey Tapiheru", "Gamaliel Tapiheru", "Maria Tiri", "Welmince Tuanakotta", "Fany Souisa", "Lia Pattipeilohy", "Meyla Noya"]
        },
        genz: {
            laki: ["Kenzo Wijaya", "Ezra Mahendra", "Vano Adriansyah", "Rayyan Alfarizqi", "Arka Putra", "Nael Pratama", "Kaelan Abrisam", "Gibran Aditya", "Liam Iskandar", "Noah Setiawan", "Raffa Alvaro", "Devan Kalingga", "Atharrazka Reyhan", "Elang Permana", "Damar Wisesa", "Bryan Domani", "Angga Yunanda", "Farel Prayoga"],
            perempuan: ["Aurelie Anjani", "Vanesha Adelia", "Naura Aisyah", "Freya Anindita", "Keysha Putri", "Aaliyah Safira", "Zaskia Calista", "Shafa Nabila", "Aurora Larasati", "Luna Kirana", "Gisella Maharani", "Cinta Kamila", "Sandrinna Zhafira", "Zoe Alishia", "Yasmin Humaira", "Adhisty Zara", "Mawar de Jongh"]
        }
    }
};
// --- END OF FILE database-nama.js ---
